### ISSUE TITLE
REBASE ROLLBACK TO 39

### ISSUE THREAD

**Issue by Evilexium** [ublue-os/bazzite#1348] opened 2024-07-10 20:36 UTC
### Describe the bug

I Installed the latest 3.5.1 and now my RGB from ASUS ROG ALLY doesnt work anymore . How can i rebase/rollback to version 39 ? nowhere in the internet is a tutorial or something that can help me . Only way to clear this out is to ask the developers here . Please give me the Terminal Promp to rollback to old v39 or any other that worked the rainbow again. And please dont close this without clear my problem and give me a solution becasue thats what i see here alot , peoples come here for a help and u guys just close everything without even try to explain a short help or a info how to do it. Just need to downgrade to make my RGB work in windows again. This issue is major and very very much of the peoples complain about this with their allys none of them got their RGB back after this Updates here.

### What did you expect to happen?

Expected to work like it did before with Bazzite-Rollback-Helper

**Comment by Tobe95** [comment] 2024-07-10 22:11
I'm not a dev but there's literally everything regarding rebase and rollback documented [here](https://universal-blue.discourse.group/t/updates-rollback-and-rebasing-on-bazzite/36).

Usually it's as easy as typing _'rpm-ostree rollback'_ and confirm with your password...

**Comment by Evilexium** [comment] 2024-07-11 03:57
Thank you Sir but i dont think that this might work becasue the KEY they use for the updates that got changed.

**Comment by KyleGospo** [comment] 2024-07-11 06:28
Try the latest update and report back if your issue is resolved.

**Comment by Bladen123** [comment] 2024-07-11 14:49
I did it tells me that there are No Updates in bazziteOS, Rebase to older Version doesnt work , and booted Windows 11 and the RGB is Dark Like its OFF If i choose Rainbow LED in Armory Create .

**Comment by KyleGospo** [comment] 2024-07-11 15:03
> I did it tells me that there are No Updates in bazziteOS, Rebase to older Version doesnt work , and booted Windows 11 and the RGB is Dark Like its OFF If i choose Rainbow LED in Armory Create .

Can you give the output of `rpm-ostree status` for me?

**Comment by Bladen123** [comment] 2024-07-11 19:24
![Uploading IMG_20240711_212346.jpg…]()

**Comment by KyleGospo** [comment] 2024-07-12 06:10
Can you update one more time for me? Be sure to use the RGB controls in HHD after you update.

**Comment by Bladen123** [comment] 2024-07-12 07:19
So it say No Updates available, HHD is all the time active RGB and i use Rainbow . bazziteOS works the RGB but my Problem is Windows RGB stoped working because of BazziteOS Look picture static ON Windows works but Rainbow stoped since i use Bazzite 
![IMG_20240712_091756](https://github.com/user-attachments/assets/5d5a8a0a-47c6-48cc-81ef-e16bf53d354a)
![IMG_20240712_091610](https://github.com/user-attachments/assets/bb4cd25d-e549-4a9b-a6fb-c0654c70e159)

**Comment by Harithz001** [comment] 2024-07-20 18:48
Has anyone found a fix to this issue? This is such a bummer as I'm receiving my Ally X in a few days time yet I am stuck, unable to re-sell my original Ally as the rainbow led is broken thanks to bazzite. I'm sure there are many others in similar predicament. Dear devs, please assist. Thank you.

**Comment by HikariKnight** [comment] 2024-08-02 11:42
> Has anyone found a fix to this issue? This is such a bummer as I'm receiving my Ally X in a few days time yet I am stuck, unable to re-sell my original Ally as the rainbow led is broken thanks to bazzite. I'm sure there are many others in similar predicament. Dear devs, please assist. Thank you.

According to the hhd dev this should be fixed now but still waiting for replies about the rainbow spiral rgb

**Comment by KyleGospo** [comment] 2024-08-26 17:34
Duplicate of https://github.com/ublue-os/bazzite/issues/1153, closing. Fix is in that issue.

**Closed by KyleGospo** 2024-08-26 17:34 UTC
Labels: bug, asus-ally
