### ISSUE TITLE
Fans keep spinning after standby on Legion go

### ISSUE THREAD

**Issue by Bastian6261** [ublue-os/bazzite#809] opened 2024-02-25 11:40 UTC
### Describe the bug

Seems like the new kernel is faulty or needs some Modifikation. If i select the old kernel, standby funcion does fully work on my Legion Go.
Someone else have the same issue on Reddit After Executing „ujust update“

### What did you expect to happen?

Fans should stop spinning after singlepress the power button 

### Hardware

Legion go with 2tb drive

**Comment by kprinssu** [comment] 2024-02-25 14:36
While the upstream issue is being fixed, you should downgrade to the last known stable version via:

`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-20240220`

**Comment by fehbari** [comment] 2024-02-25 21:05
Experiencing the same on the ROG Ally. Booting the previous version with grub works fine, so a rollback to the previous release should indeed work until the issue is fixed.

**Comment by spongeyperson** [comment] 2024-02-27 00:33
>I'm also having a lot of random freezes that force me to shutdown by holding the power button.

I was also having the freezing that forces me to shutdown on the newer version, changing to the version suggested by kprinssu seemingly fixed this issue. **I am on the Legion Go**, but it seems the Z1 Extreme in general seems to have had some regression in either the latest kernel, or the latest bazzite version.

**Comment by codevski** [comment] 2024-03-02 12:51
> Experiencing the same on the ROG Ally since updating. I'm also having a lot of random freezes that force me to shutdown by holding the power button.
> 
> Booting the last version with grub everything works fine, so a rollback to the previous release should indeed work until the issue is fixed.
> 
> _Update:_ I can confirm rolling back fixes the issues for now. To do it on the Ally:
> 
> ```
> rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:39-stable-20240220
> ```
> 
> To list other versions if the Feb 20th one doesn't work for you:
> 
> ```
> skopeo list-tags docker://ghcr.io/ublue-os/bazzite-ally | grep -- "-stable-" | sort -rV
> ```

Is the issue being tracked? Just wondering when would it be safe to update

**Comment by lowpayne** [comment] 2024-03-03 19:09
Is there a stable version or a solution to this problem?

**Comment by KyleGospo** [comment] 2024-03-03 19:18
> Is there a stable version or a solution to this problem? 

https://github.com/ublue-os/bazzite/issues/809#issuecomment-1963061009

**Comment by lowpayne** [comment] 2024-03-03 20:23
I know that i meant about latest build

**Comment by kprinssu** [comment] 2024-03-03 23:50
> I know that i meant about latest build

It won't be fixed until whatever combination of packages is resolved upstream - it's not a Bazzite problem ,most likely Mesa or the Kernel. Just use the Feb. 20, 2024 build until it's fixed.

**Comment by lowpayne** [comment] 2024-03-04 09:05
Am I missing something not being On The latest build ?

**Comment by KyleGospo** [comment] 2024-03-04 09:41
> Am I missing something not being On The latest build ?

Very little at this time, and given the nature of kernel bugs and how fast they're usually fixed this should be resolved before you are missing something.

**Comment by kprinssu** [comment] 2024-03-08 12:19
It looks like the newer 6.7.7 kernel fixed the suspend issue. 

I use the following command to go back to the 39-stable branch:


`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-stable`

**Comment by Bastian6261** [comment] 2024-03-08 12:46
When i Type This in, i‘ll get an error : old and new refs Are equal.
Any idea?

**Comment by gyorgys** [comment] 2024-03-09 21:00
> It looks like the newer 6.7.7 kernel ~fixed~ partially fixed the suspend issue. On further testing, my Legion Go can go through a sleep/wake cycle, but the fans will keep running. This is not ideal as those fans will use up a lot of power when on battery.

I tried stable today. It looks like fans will just remain on whatever speed they were when suspend was initiated. If I force full fan speed from decky plugin, then suspend, fans will continue to blast at full speed.

I have Beta BIOS 29.1

**Comment by kprinssu** [comment] 2024-03-09 23:29
That's the exact same behaviour I am seeing as well. I am on the beta 29.1 BIOS too.

**Comment by Bastian6261** [comment] 2024-03-10 23:37
Same here still. Need an Update so the fans turn off as i cant Update hhd for the gyro fix :(

**Comment by aarron-lee** [comment] 2024-03-11 12:35
part of dmesg on stable from 3/11/24, indicates failure to enter deepest sleep state

[dmesg.txt](https://github.com/ublue-os/bazzite/files/14558613/dmesg.txt)

**Comment by lowpayne** [comment] 2024-03-14 12:13
They fixed that bug.🙂

**Comment by kprinssu** [comment] 2024-03-14 12:49
Thanks @lowpayne, for future reference this is how we get back to the stable builds:

https://github.com/aarron-lee/legion-go-tricks/?tab=readme-ov-file#known-bugs

**Comment by aarron-lee** [comment] 2024-03-14 15:10
bug is confirmed fixed, could probably close this issue.

for future reference, this is for to get back to stable on the Legion go:

`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable`

replace `bazzite-deck` with `bazzite-ally` or `bazzite-deck-gnome`, depending on the image you are on

**Closed** 2024-03-14 15:18 UTC
