### ISSUE TITLE
Application launcher doesn't show when the panel is hidden

### ISSUE THREAD

**Issue by Tikaiz1** [ublue-os/bazzite#1387] opened 2024-07-20 23:51 UTC
### Describe the bug

My panel in Plasma is set to dodge windows and when the bar is hidden, I can't open the application launcher menu using the meta key. This only happens if I click on two windows while the panel is hidden, otherwise it works fine. When i move my mouse over the panel, it then acts as if all the keypresses happened at once.

### What did you expect to happen?

I expected the application menu to show regardless if I have my bar hidden or shown.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:25eb70d16d0754c4dd902294e43579d413919508e72a31ee8862c0bf442a9485
                  Version: 40.20240717.0 (2024-07-17T17:42:01Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:6575482de703e10a30ec882f7d04b2bf179deee3fd7d68056409758d6e63b133
                  Version: 40.20240717.0 (2024-07-17T17:42:01Z)
```

### Hardware

Processors: 12 × AMD Ryzen 5 3600X 6-Core Processor
Memory: 16 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
Motherboard: Asrock B550 Pro4

**Comment by gordon-boom** [comment] 2024-07-22 01:54
This is a known issue with the Nvidia driver. The current status of the issue is "they have a fix ready". Not sure when they plan to actually deploy it.

See links below.

https://forums.developer.nvidia.com/t/kde-plasma-wayland-explicit-sync-driver-bug/295081
https://github.com/NVIDIA/egl-wayland/issues/111

**Comment by Tikaiz1** [comment] 2024-07-22 16:39
Alright, thanks for letting me know.

Should I close this issue now, or is it better if i leave it open for now?

**Comment by gordon-boom** [comment] 2024-07-24 10:27
I would leave this open until someone can confirm it's been fixed. It helps people know whether or not this issue should be fixed in the future if they run into similar problems.

**Closed** 2024-11-06 16:06 UTC
Labels: bug
