### ISSUE TITLE
Steam Deck Desktop Mode (KDE) Results In plasmashell crashes

### ISSUE THREAD

**Issue by pastram-i** [ublue-os/bazzite#1145] opened 2024-05-17 23:32 UTC
### Describe the bug

Gaming mode works as expected. 

When switching to Desktop Mode, the Desktop is seen quickly before multiple plastmashell crashes are displayed until desktop goes to a black screen background. 

### What did you expect to happen?

Desktop Mode (KDE) runs as expected. 

### Output of `rpm-ostree status`

```shell
N/A (unless I can run in Gaming Mode somehow? Let me know and I’ll provide).
```

### Hardware

Steam Deck (Non-OLED) 256gb

### Extra information or context

N/A

**Comment by miguelbaldi** [comment] 2024-05-17 23:38
Same thing with Asus ROG Ally.
Fresh install, following the official guide. Game mode starts fine, when I try to change to Desktop Mode to finish configuration, plasmashell crashes.
Looking at the stacktrace, seems to be something on `libc`

**Comment by pastram-i** [comment] 2024-05-17 23:42
+1 report via GPD Win Mini 2204 (8840) [via Discord](https://discord.com/channels/1072614816579063828/1241046751725617163/1241046751725617163)

**Comment by miguelbaldi** [comment] 2024-05-18 04:35
There's another user on Reddit reporting the exact same issue. He posted a video and a pastebin on the comments with stacktrace:
https://www.reddit.com/r/LinuxOnAlly/s/zNfc8C35JS

**Comment by b-lechalupe** [comment] 2024-05-18 10:56
Hello here!

Same issue with a ROG Ally freshly installed.

During setup, I could access the desktop with the welcome window that do some setup, then I started the gamemode for the first time and everything worked well.

Now that the gamemode is setup and running, any attemp to switch to desktop mode briefly display the background and the "Return to Gaming Mode" icon, then 3 crash handler window appear all referencing plasmashell, if you close these 3 window, you face a black screen.

With a physical keyboard plugged in, I can still open Ptyxis terminal and attempt something (Just press ALT + F2 then type "Ptyxis" then enter).
Running `qdbus org.kde.Shutdown /Shutdown org.kde.Shutdown.logout` will actually work and bring me back to the gamemode without needing to hard shutdown the machine.

It's my first experience with Bazzite. I love it already, buuuuuuuut... I hope we'll have a working desktop soon :)

**Comment by Topuz** [comment] 2024-05-18 21:32
Same here, fresh install on ROG Ally.

**Comment by pastram-i** [comment] 2024-05-20 15:41
Thanks to @b-lechalupe for [letting me know I can still get to the terminal when plasma crashes](https://github.com/ublue-os/bazzite/issues/1145#issuecomment-2118778181), and finding the [documentation on rollbacks](https://universal-blue.discourse.group/docs?topic=36), I want able to successfully rollback to a working build (`40-stable-20240517`). 

If you want to explore other builds, you can with the below command -
`skopeo list-tags docker://ghcr.io/ublue-os/bazzite | grep -- "-stable-" | sort -rV `

This requires an external keyboard to do. 

Steps:
- Switch to desktop mode
- Plug in external keyboard
- Allow plasmashell crashes to take place
- Press Alt-F2
- Type “Ptyxis” and hit enter
- Install the working build -
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:40-stable-20240517`
- Wait (there’s no progress bar, and this can take several minutes)
- When complete, type `systemctrl reboot` and hit enter to restart the device
- Once booted, switch to desktop mode
Desktop mode now works as expected for me!

**Comment by martinville** [comment] 2024-05-20 17:04
Looks like the issue is caused by the theme called "Vapor" that is making use of an old JSON format for plasmashell theming along with some image formats that is not supported.

I tried switching the theme using 
`lookandfeeltool -a org.kde.breeze.desktop`

But unfortunatly it still crashes.

If you are able to replicate the issue, let plasmashell crash and from the terminal "ALT+F2" search Ptyxis, 
Launch `plasmashell` you will see that it's trying to start plasmashell over and over printing the error message causing it to fail.

**Comment by lu0510** [comment] 2024-05-21 11:32
Hello , still the probleme is there for me gpd win 4 , here is the crashlog :
[crashlog.txt](https://github.com/ublue-os/bazzite/files/15389167/crashlog.txt)
with a older build it works perfekt with bazzite-rollback-helper rebase 40-20240427
i hope it will fixed

**Comment by martinville** [comment] 2024-05-21 16:27
Still doesn't work for me, I re-downloaded the latest image from https://bazzite.gg/ and tried again only to find plasmashell still crashing. I have a feeling I simply installed the same broken OS as before because the file's are not versioned. 👎 

It's pitty was quite excited to try this out. 

Goodluck with this.

**Comment by mrluizandre** [comment] 2024-05-24 00:00
Same here with ROG Ally downloaded the .iso today and the problem still happens.

**Comment by pixelbart** [comment] 2024-05-24 17:00
same

**Comment by KyleGospo** [comment] 2024-05-24 22:49
https://bugs.kde.org/show_bug.cgi?id=487466

**Comment by pastram-i** [comment] 2024-05-24 23:29
In the meantime for anyone wanting desktop mode - I recommend rolling back to a working image, as [I mentioned above](https://github.com/ublue-os/bazzite/issues/1145#issuecomment-2120713561).

**Comment by Mattheish** [comment] 2024-05-27 11:39
I just encountered this issue too when installing bazzite-deck with newly downloaded on my Steam Deck LCD. 

Tried the suggested rolling back but issue persisted. Steps I took to solve are as follows:

1. rebase to bazzite-deck:39-stable
2. Go to desktop mode and change global theme to Fedora  (Appearance and Desktop layout)
3. rebase to bazzite-deck:stable
4. Go to desktop mode and change global theme back to Vapor

**Comment by KyleGospo** [comment] 2024-05-27 17:59
Plasma Shell 6.0.5 is now present on the latest stable and testing builds, and I have some confirmations that it fixes this issue as promised. Would appreciate some more feedback so we can close this finally.

**Comment by AzMilk50** [comment] 2024-05-27 21:36
> Plasma Shell 6.0.5 is now present on the latest stable and testing builds, and I have some confirmations that it fixes this issue as promised. Would appreciate some more feedback so we can close this finally.

Rebasing to the latest Ally build has fixed it for me.

**Closed** 2024-05-27 21:37 UTC
