### ISSUE TITLE
Volume Issues on Deck 

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#193] opened 2023-08-25 19:57 UTC
On the Steam deck, the max volume seems lower after a recent update. There was a time where the boot sound was wildly loud, but how even with volume set to the max, it is still too quiet compared to Steam OS.

**Comment by KyleGospo** [comment] 2023-08-25 20:05
A volume change we made was dropped when the needed firmware for the amps was added, but I agree it's still too low.

Reverted the reduction, should be as loud again next-update.

**Comment by knaackville** [comment] 2023-08-27 17:12
Not sure if this is the same issue or not, but on random reboots (may be primarily when it is a hard reboot due to a system freeze?), the volume seems to be set to max during the initial steamos boot sound, that continues in game or other apps until manually adjusted.  The slider looks to be where it was previously set during this time at an appropriate volume, but it's not respecting that setting.

Seems to be hard to reproduce on my end, but wakes you up when it happens...

**Comment by KyleGospo** [comment] 2023-08-31 23:36
These issues should be entirely fixed as of this morning

**Closed** 2023-08-31 23:36 UTC

**Comment by unicornsandcandies** [comment] 2023-09-05 20:22
> These issues should be entirely fixed as of this morning

I still have this issue

**Comment by NightHammer1000** [comment] 2023-09-06 17:14
Yeah. Still also have this on some Reboots. Seems completly Random at this point :/

**Comment by Kohega** [comment] 2023-09-07 22:14
Okay, after a bit of searching, I stumbled accross a message on the Discord about checking Alsamixer, and it did the trick.
Upping the Left & Right Analog PCM value fixed the low audio for me.
![image](https://github.com/ublue-os/bazzite/assets/45211407/db20ba7b-12e4-4cde-8d89-6f8eaff29f16)

**Comment by unicornsandcandies** [comment] 2023-09-07 23:02
> Okay, after a bit of searching, I stumbled accross a message on the Discord about checking Alsamixer, and it did the trick. Upping the Left & Right Analog PCM value fixed the low audio for me. ![image](https://user-images.githubusercontent.com/45211407/266452728-db20ba7b-12e4-4cde-8d89-6f8eaff29f16.png)

Did you found anything on randomly maxed volume?

**Comment by Kohega** [comment] 2023-09-08 10:38
> Did you found anything on randomly maxed volume?

I did not experienced this random volume issue. I tried several different reboot and did not experience a high volume a single time.
