### ISSUE TITLE
No light on playstation dual sense controller when connected over bluetooth

### ISSUE THREAD

**Issue by ZainAjam** [ublue-os/bazzite#1177] opened 2024-05-26 13:58 UTC
### Describe the bug

When playstation dual sense controller is connected over bluetooth to minisforum HX99G, the light on the controller does not come on. There is no way to know the controller is even powered on other than to see it work on the screen.

### What did you expect to happen?

I expect the light on the dual sense controller to be on

### Hardware

HTPC image of Bazzite v3.0.1
Minisforum HX99G
2 x 16gb DDR5 4800mhz ram
1 x 500gb NVME storage drive (Bazzite installed on)
1 x 1000gb NVME storage drive (formatted as ext4 and set for mounting with KDE partition manager)
Xbox Series S controller with Xbox Wireless Dongle receiver
Pepper jobs remote control with usb receiver

**Comment by HikariKnight** [comment] 2024-06-05 23:32
Hmm, i suspect this might be an upstream issue, it worked last month however i am unsure when this might have broken since i was personally stuck on the image from May 2nd, but does not work for me now either.

You should be able to control the LED from steam, but it since it is not working in general i am unsure if the issue is in bluez, hid_playstation or steam itself.
I will add the label upstream for now until we get some more data.

**Comment by HikariKnight** [comment] 2024-06-07 15:53
Seems to be fixed in the newest image @ZainAjam

**Comment by HikariKnight** [comment] 2024-06-07 18:04
> > Seems to be fixed in the newest image @ZainAjam
> 
> Which image is that? I used htpc version 3.0.1 (the latest release) when I noticed this issue. Is there a later image somewhere?

run `rpm-ostree status -b`
the version line will show something like `40.20240605`
40 is the fedora version, the rest is the image date (when the bazzite image was made)

the version you are talking about is just the "public release" version with the list of all the recent changes from the previous "version"

**Comment by ZainAjam** [comment] 2024-06-07 18:08
I see. Thank you.

Is this terminal command the only way to run updates or is there a way I
can run the image update from within steam gaming mode?

**Comment by ZainAjam** [comment] 2024-06-07 18:32
> Seems to be fixed in the newest image @ZainAjam 

Thank you. I've gone in to desktop mode and run system upgrade and it fixed the issue. 

I thought the gaming mode "check for update' was the same as"system upgrade" but it seems that the system upgrade runs more frequent updates than the "check for update" option

**Comment by KyleGospo** [comment] 2024-06-07 18:33
It's exactly the same

**Comment by ZainAjam** [comment] 2024-06-07 18:35
> It's exactly the same, runs the same command

How strange. When I run the 'check for updates', it says no updates available, but when I ran the desktop system upgrade, it found and upgraded things..

**Comment by HikariKnight** [comment] 2024-06-07 20:27
> > It's exactly the same, runs the same command
> 
> How strange. When I run the 'check for updates', it says no updates available, but when I ran the desktop system upgrade, it found and upgraded things..

they both run `ujust update`

**Closed** 2024-06-08 07:53 UTC
Labels: bug, upstream
