### ISSUE TITLE
Steam BPM Very Laggy

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#1211] opened 2024-06-07 22:37 UTC
Sinilar to #1160 except this is on a Framework 16 with the AMD GPU instead of NVIDIA. Following the workaround in the last comment resolves the issue.

**Comment by KyleGospo** [comment] 2024-06-07 22:40
This one is on our radar, at this time on dual AMD GPU laptops if steam is properly set up to use the proprietary GPU it will fail to render a UI unless you also disable GPU acceleration in the built-in chromium. 

We will reverse that flag as soon as the issue is fixed in the Steam client.

**Comment by KyleGospo** [comment] 2024-06-17 21:45
This will be fixed in the next update.

**Closed by KyleGospo** 2024-06-17 21:45 UTC
Labels: upstream
