### ISSUE TITLE
(bazzite-gnome-deck:39) No controls for GPU in menu since update

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#505] opened 2023-11-03 08:52 UTC
Here's how it looks, both off and on.

![IMG_20231103_095308793](https://github.com/ublue-os/bazzite/assets/112720004/2262bb0d-f358-4b84-b41d-8fcf2d8a0d4a)
![IMG_20231103_095317815 MP](https://github.com/ublue-os/bazzite/assets/112720004/1960d1b7-0781-4c0e-83f2-3466890478b3)

As seen on pictures, there's no way to use this setting.

**Comment by unicornsandcandies** [comment] 2023-11-03 15:38
Okay, there's something REALLY wrong with this release and graphic drivers 

That's what happens to my screen after launching yuzu/some non steam games:
![IMG_20231103_163534720 MP](https://github.com/ublue-os/bazzite/assets/112720004/a759ae2c-29cc-4f74-8c97-b026f2ee8571)

**Comment by unicornsandcandies** [comment] 2023-11-03 15:42
> Okay, there's something REALLY wrong with this release and graphic drivers
> 
> That's what happens to my screen after launching yuzu/some non steam games:
> 
> ![IMG_20231103_163534720 MP](https://user-images.githubusercontent.com/112720004/280333758-a759ae2c-29cc-4f74-8c97-b026f2ee8571.jpg)
> 
> @KyleGospo

How to recreate this 

undocked:
- launch game mode
- open yuzu and go to settings

Docked 
- launch any game on Cemu, preferably Zelda botw

Whole screen starts to have weird colors and glitching like it's broken.

**Comment by KyleGospo** [comment] 2023-11-03 18:23
Not able to reproduce this here, just launched TOTK without issue on the latest gnome-deck:39

Are you using the flatpaks or some other method of installing CEMU & Yuzu?

**Comment by unicornsandcandies** [comment] 2023-11-03 18:26
> Not able to reproduce this here, just launched TOTK without issue on the latest gnome-deck:39
> 
> Are you using the flatpaks or some other method of installing CEMU & Yuzu?

I'm using emudeck and default config. The issue is also visible on steam link. Can I rebase it once again?

**Comment by unicornsandcandies** [comment] 2023-11-03 18:35
> Those would be the flatpaks then which have their own copy of Mesa, on top of that every single Bazzite 39 build has had the same build of Mesa. Something else is going on here.

I would gladly give any outputs or logs needed. I'm just not sure where to look for the issue. I've tried rebasing to 38 again but it gave me a gpg error

**Comment by unicornsandcandies** [comment] 2023-11-03 19:11
Big update:
- Issue happens on both kde and gnome version.
- screen glitching visible only on FSR scaling turned on apparently 
- No access to GPU quick settings no matter what 

Does it help to replicate the issue for you?

**Comment by unicornsandcandies** [comment] 2023-11-03 21:42
![Screenshot_20231103-202410_Steam Link](https://github.com/ublue-os/bazzite/assets/112720004/1b94ee31-bc64-4202-a870-a63f977785f5)

**Comment by unicornsandcandies** [comment] 2023-11-03 22:15
Managed to roll back to DECK-GNOME:38. Can confirm that there's zero issues there.

**Comment by KyleGospo** [comment] 2023-11-08 04:05
All fixed in stable build

**Closed by KyleGospo** 2023-11-08 04:06 UTC
