### ISSUE TITLE
Steam menu fps limitation to off not working properly

### ISSUE THREAD

**Issue by darkkilltec** [ublue-os/bazzite#263] opened 2023-09-05 08:34 UTC
Hi
yesterday I installed the default bazzite version for the steam deck, installation and setting up worked quite smoothly.
But then I started to play Baldurs Gate 3 and wanted to test the performance.

In game no fps limitation set, then 30 fps was set in the battery tab in steam overlay when setting to "off" far right, the game is just stuck. Seeing no movement and the performance overlay also not changing, moving the slider away from off instantly shows fps going up from a sudden one digit back to 20 to 30 fps. So it seems turning the fps limitation off does something, but not the intendant.

Downloaded the newest release yesterday, installed default bazzite OS for steam deck with KDE.

**Comment by KyleGospo** [comment] 2023-09-05 18:03
Hi there, a video would be helpful for this issue. I'm not able to reproduce it on two different Steam Decks and a Desktop.

**Comment by darkkilltec** [comment] 2023-09-05 19:38
https://youtu.be/F9Dy_PmTnfo

**Comment by darkkilltec** [comment] 2023-09-06 19:56
a fresh install changed something ...
when i start the game right now the fps limiter is stuck on off, when i move it to anything left it gets stuck now, moving it to off works fine..lol
I just did a fresh install and reverted the BIOS back to optimal settings. Had VRAM set to 4gb.

**Comment by kubepy** [comment] 2023-09-07 04:02
Also my bazzie-deck-gnome (38-20230906) on steamde.
The game is just stucking, only audio works when the steam overlay when the fps limitation setting to "off" far right.

I have no idea how to investigate the reason.

**Comment by KyleGospo** [comment] 2023-09-10 08:23
Should be fixed as of the latest version, no longer able to reproduce in any game here.

**Comment by kubepy** [comment] 2023-09-11 08:48
Thank you. Yes, I confirmed it is fixed!

**Closed** 2023-09-11 23:34 UTC
