### ISSUE TITLE
Bazzite failing to update after 3.5.0 update

### ISSUE THREAD

**Issue by al12gamer** [ublue-os/bazzite#1317] opened 2024-07-02 17:42 UTC
### Describe the bug

When running `ujust update` to update the system in the background while playing some YouTube in Vivaldi in the foreground, it seems the system fails to update due to  a possible signature error?

### What did you expect to happen?

I expected the system to update without error.

### Output of `rpm-ostree status`

```shell
Status output:

gamer@fedora:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:d23de6a06070e3b4de06353f4a8c1939817164fae55613a0b91c1045bec5f2b2
                  Version: 40.20240701.0 (2024-07-02T00:20:03Z)
          LayeredPackages: edk2-ovmf qemu virt-manager

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:dcf0c28f284a613759ea0b1da0c10ba8744dc13f2de90fa5de5d6be49f0a01f5
                  Version: 40.20240630.0 (2024-06-30T20:42:59Z)
          LayeredPackages: edk2-ovmf qemu virt-manager
```

### Hardware

System hardware for context:
```
gamer@fedora:~$ cat /sys/devices/virtual/dmi/id/product_name
AB350 Gaming-ITX/ac
gamer@fedora:~$ sudo dmidecode -t bios
# dmidecode 3.6
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: American Megatrends Inc.
	Version: P7.40
	Release Date: 10/27/2022
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 16 MB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		BIOS ROM is socketed
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 5.17
```
and a fastfetch:
```
                                          gamer@fedora
     %%%%%%====%%%%%%%%%%                
   %%%%%%%%    %%%%%%%%%%%%%%             󱋩  bazzite-deck:stable 
  %%%%%%%%%    %%%%%%%%%%%%%%%%           󰣛  Fedora Linux 40 (Kinoite) x86_64
  %%%%%%%%%    %%%%%%%%%%%%%%%###           Linux 6.9.6-201.fsync.fc40.x86_64
  %%%%%%%%%    %%%%%%%%%%%%%######        󰅐  14 hours, 3 mins
  ==                  =======######       󰔠  Spawned on Jun 27 2024
  ==                  =========#####     
  %%%%%%%%%    %%%%%%%####======#####     󰾰  AB350 Gaming-ITX/ac
  %%%%%%%%%    %%%%%#######=====#####     󰻠  AMD Ryzen 5 3600 (12) @ 4.21 GHz
  %%%%%%%%%    %%%#########=====#####     󰍛  AMD Radeon RX 5700 XT @ 0.01 GHz [Discrete]
  %%%%%%%%%    %%##########=====#####       5.31 GiB / 15.54 GiB (34%)
  %%%%%%%%%====###########=====######       810.77 GiB / 906.19 GiB (89%) - ext4 [External]
   %%%%%%%%====#########======######        323.62 GiB / 475.35 GiB (68%) - btrfs [Read-only]
    %%%%%%%=====#####========######       󰍹  3840x2160 @ 60Hz (as 1920x1080) [External]
     %%%%###===============#######       
      %#######==========#########         󰕮  KDE Plasma 6.1.1
        #######################             KWin (Wayland)
          ###################               bash 5.2.26
              ###########                   ptyxis-agent
                                          󰏖  2948 (rpm), 46 (flatpak-system), 31 (flatpak-user)

                                           ● ● ● ● ● ● ● ●

```

### Extra information or context

Output from the update:
```
gamer@fedora:~$ ujust update

── 11:38:02 - System update ────────────────────────────────────────────────────
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: cryptographic signature verification failed: invalid signature when validating ASN.1 encoded signature
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:273
```

**Comment by castrojo** [comment] 2024-07-02 17:45
Duplicate of: #1316

**Comment by al12gamer** [comment] 2024-07-02 17:47
Oh, sorry, I didn't see that one

**Closed** 2024-07-02 17:49 UTC
Labels: bug
