### ISSUE TITLE
No Wi-Fi after latest update

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1229] opened 2024-06-14 23:13 UTC
### Describe the bug

I had a little break from technology. Today I've updated my deck to the newest bazzite (literally a moment ago) and the wifi is missing. Both in gaming and in desktop mode, the os acts like there's no wifi driver and doesn't see any wifi connection.

Here's the log from current boot, from ujust:
[log.txt](https://github.com/user-attachments/files/15844687/log.txt)

I really need this to work right now. How to rebase to the working version properly?

### What did you expect to happen?

Working wifi

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:fa26753fd39c074f9ba6895460115d0f0fd066514ce9ca2f2ca42b49007927f7
                  Version: 40.20240613.0 (2024-06-14T20:10:19Z)
          LayeredPackages: plymouth-theme-script
            LocalPackages: pedro-raccoon-1.1-1.1.x86_64
                Initramfs: regenerate

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:26b268ec5de0c1618f0618855761b2da934614dfb060fd5d69ffed4fad14d2b9
                  Version: 40.20240611.0 (2024-06-11T16:59:32Z)
          LayeredPackages: plymouth-theme-script
            LocalPackages: pedro-raccoon-1.1-1.1.x86_64
                Initramfs: regenerate
```

### Hardware

Galilieo
Steam Deck OLED

**Comment by KyleGospo** [comment] 2024-06-14 23:16
Not able to reproduce on my LCD or OLED

**Comment by unicornsandcandies** [comment] 2024-06-14 23:19
> Not able to reproduce on my LCD or OLED

What can I do to repair this? Everything worked fine before the upgrade

**Comment by KyleGospo** [comment] 2024-06-14 23:19
> > Not able to reproduce on my LCD or OLED
> 
> What can I do to repair this? Everything worked fine before the upgrade

Try rolling back, but I'm not sure why this issue would affect you and not me on the same hardware.

**Comment by unicornsandcandies** [comment] 2024-06-14 23:44
> > > Not able to reproduce on my LCD or OLED
> > 
> > 
> > What can I do to repair this? Everything worked fine before the upgrade
> 
> Try rolling back, but I'm not sure why this issue would affect you and not me on the same hardware.

Works fine on "40-stable-20240611"

**Comment by Raltay** [comment] 2024-06-15 07:25
Same story for me, WiFi on my Steam Deck OLED died on the latest stable bazzite-deck-gnome.

**Comment by unicornsandcandies** [comment] 2024-06-15 07:32
> Same story for me, WiFi on my Steam Deck OLED died on the latest stable bazzite-deck-gnome.

I've managed to rebase with bluetooth tethering on desktop mode. It helps but there's definitely an issue with this update. I attached logs but if you boot without the splash (in the text mode, click escape) there's also a lot of issues appearing quickly, like a failed firmware loading

**Comment by APoorDev** [comment] 2024-06-15 11:33
Same here, Steam Deck OLED has no wifi after latest update. A rollback to 40.20240611.0 fixes it.

**Comment by JediMasterChief** [comment] 2024-06-15 23:47
I am having this issue as well on my Steam Deck, and I just installed Bazzite on it today, no prior versions to roll back to. I have a dock and ethernet, so I still have options for network access in the mean time.

**Comment by KyleGospo** [comment] 2024-06-16 01:08
Should be fixed in the latest build.

**Comment by JediMasterChief** [comment] 2024-06-16 02:03
Can confirm that, at least on my end, the issue is now fixed. Thank you!

**Closed** 2024-06-16 02:19 UTC
