### ISSUE TITLE
Power savings not working.

### ISSUE THREAD

**Issue by darkkilltec** [ublue-os/bazzite#264] opened 2023-09-05 08:38 UTC
I installed default bazzite with KDE for Steam Deck.
I loved the power savings option on the Steam OS, just pressing the power button and continue to play whenever.

Furthermore, I was playing Baldurs Gate 3 pressed power button, screen goes blank and everything seems off. Trying to start again with pressing the power button did nothing. 

Battery was full.
Next Morning tried power button again to see if it starts now, no luck so pressed power button again for more than 5 seconds and again nothing.
Hooked to power supply and saw the steam deck come back to life and the battery was empty completely drained.

I love the idea and the project, I do not know if I can help with development but right now I can help with testing stuff, finding problems and reporting them. I am a software developer from Germany had mostly C# experience but since last year shifted to JS and ts with web apps.

**Comment by darkkilltec** [comment] 2023-09-05 18:01
So i tried this again directly from game mode without being ingame, still same. Then tried this from desktop mode, again no change.

after pressing the power button(for it to come back) i hear the fan going very loud but nothing happens on screen, only way right now to get it back is a hard 5 sek. reset.

This would be a reason for me to go back to the original StemOS because this feature is amazing, being able to power save mode and after 15 mins going back directly to the game is awesome.

**Comment by KyleGospo** [comment] 2023-09-05 18:02
Can you record a video? I'm not able to reproduce this on any hardware.

**Comment by darkkilltec** [comment] 2023-09-05 19:55
https://youtu.be/7Kxrk9f6izI

**Comment by darkkilltec** [comment] 2023-09-05 20:41
i have more infos, it seems after going to power safe, then pressing power buttons, increasing or decreasing sound gives me a sound, so it seems like just the screen is blank, pressing it again, now i dont get sound feedback but the pads give this rumble feedback while going over them, pressing the power button further does not change anything anymore, the thumb pads just rumble. any other input does not give any feedback.

**Comment by KyleGospo** [comment] 2023-09-05 20:46
Sounds like it's simply not going to sleep, but I'm still unable to produce both of your issues even after a complete reinstall on real hardware. I'll keep digging.

**Comment by darkkilltec** [comment] 2023-09-05 20:54
sorry to hear that, i will try a fresh install tomorrow, i had set a user password in the anaconda installer and deactivated root.

**Comment by kubepy** [comment] 2023-09-06 17:21
As I know when you push the button key, it calls the script `~/.steam/root/ubuntu12_32/steam -ifrunning steam://shortpowerpress` will show the steam animation logo first then go to `suspend.target` to suspend the machine.

```
sudo rpm -ql jupiter-hw-support-btrfs-0.0.git.786.e6e43b17-1.fc38.x86_64 | grep button
/usr/lib/hwsupport/power-button-handler.py
/usr/lib/udev/rules.d/99-power-button.rules

$ cat /usr/lib/hwsupport/power-button-handler.py
```
```
def longpress():
	os.system( "~/.steam/root/ubuntu12_32/steam -ifrunning steam://longpowerpress" )
	global longpresstimer
	longpresstimer = None

if powerbuttondev != None:
	for event in powerbuttondev.read_loop():
		if event.type == evdev.ecodes.EV_KEY and event.code == 116: # KEY_POWER
			if event.value == 1:
				longpresstimer = threading.Timer( 1.0, longpress )
				longpresstimer.start()
			elif event.value == 0:
				if longpresstimer != None:
					os.system( "~/.steam/root/ubuntu12_32/steam -ifrunning steam://shortpowerpress" )
					longpresstimer.cancel()
					longpresstimer = None

	powerbuttondev.close()
	exit()

print ( "power-button-handler.py: Can't find device for power button!" )
```

if the steamdeck suspend button doesn't work, I just guess whether there is some bios settings was changed causing this issue.
I recommend to flash the latest bios firmware manually first that could reset the default bios settings. Everything should be ok.
```
sudo /usr/share/jupiter_bios_updater/h2offt /usr/share/jupiter_bios/F7A0116_sign.fd -all -AC
```

If it still doesn't fix, suggest you use the `sosreport` command to collect your machine logs to investigate.
the logs will be create in `/var/tmp/sosreport-*tar.xz` folder.

```
sudo -i
sosreport
```

**Comment by darkkilltec** [comment] 2023-09-06 20:11
so where do i put the reports for investigation

**Comment by kubepy** [comment] 2023-09-07 03:55
> so where do i put the reports for investigation, did a fresh install and reverted BIOS back to optimized Settings, but no change.

I think you may save it to person drive, like gdrive for sharing the logs for investigation.

**Comment by noelmiller** [comment] 2024-01-15 19:36
Fixed in next release. Fsync kernel has a patch which should fix this.

**Closed by noelmiller** 2024-01-15 19:36 UTC
